language: ruby
rvm:
  - 1.9.3
services:
  - mongodb
env:
  - secure: "MfexnzrmRv3IBJTq0umpa0XqpklthyVAalPHgf2oDuGBm9g8Ywk+lP3goeFW80UGD0CsLhIp4EZwjd4Bl3r6pJspPiY0gBY+3C6mrEIlSCGu3OymSvU8EIrUfquZMpk3OpXiIYw9Fm4IyE07r8oSItKUtEEJLuYjwDWEMsQzI48="
