language: ruby
rvm:
  - 1.9.3
services:
  - mongodb
env:
  - secure: "dsggwdMklqdYOp8Ygp5QFvmR7xKVR2gaY9pRtPNGAYHLaLRlRVxA+l6EP/tLewqTE2cFKHjc7HVZEiu219P25ZO/p9DPF12RWE6d6szr73bVo+xvYFChMrvH5W2RB4xz0N0SFApj8kxD92zNz9qcKQcdVs6+U8jHUHDtLtWGGkY="
