development:
  clients:
    default:
      database: sightings
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: sightings_test
      hosts:
        - localhost:27017
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  clients:
    default:
        uri: <%= ENV['MONGOHQ_URL'] %>